# Generated by Django 6.0.6 on 2026-06-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restuarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restuarant_name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('picture', models.URLField(default='https://m.media-amazon.com/images/I/71mlk+5TszL._AC_UF894,1000_QL80_.jpg')),
            ],
        ),
    ]
