# Generated by Django 6.0.6 on 2026-06-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromaApp', '0003_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='aromaApp.user')),
                ('items', models.ManyToManyField(related_name='carts', to='aromaApp.items')),
            ],
        ),
    ]
